### ISSUE TITLE
All core Application instances migrated to ApplicationV2 and ThemeV2

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/foundryvtt#11184]
## Requirements
- [x] Create a tracking spreadsheet for every application in our codebase where we can survey its migration status. These become individual issues which we can track as a sub-project or project view.
- [x] Prioritize major applications and associate related issues to the highest priority apps.
- [x] Ensure that each migrated application works well for both "light" and "dark" color preferences.
- [x] Early-adopt "Theme V2" layers to enforce that our core styles are designed with layers in mind.
- [x] Evaluate whether we need to wrap all system and module CSS within a layer. Include some manifest field allowing modules to opt out of automatic layering.
- [x] Ensure all application classes are migrated to ESModules
- [x] Evaluate and consider alternative rendering backends (Svelte?) before making a final re-committment to Handlebars
- [x] Ensure all Handlebars template files are migrated to `.hbs` extensions
- [x] Ensure that all forms that are backed by a data model are using data-model based sheet rendering and localization.
- [x] Establish a set of minimum a11y standards that we impose for all applications.
- [x] Make extensive use of new standardized CSS variables to make theming and restyling easy to do in a comprehensive and consistent way.
- [x] Evaluate opportunities for meaningful layout or UX changes for the non-windowed elements of our interface.
  - Sidebar
  - Scene Navigation
  - Hotbar
  - Players
  - Scene Controls
  - AV Frames
- [ ] Evaluate more widespread use of Canvas legends similar to the one added for Scene Regions

**Comment by JPMeehan** [comment]
You have an issue for layers already btw: https://github.com/foundryvtt/foundryvtt/issues/6842

**Comment by LukasPrism** [comment]
Can this please be included as part of the sidebar UX evaluation: https://github.com/foundryvtt/foundryvtt/issues/4883
