### ISSUE TITLE
v11 Migration Guides & Documentation

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#9225]
Some candidate topics for their own migration guides and/or more in-depth API docs:
- [ ] New `base` type and module-provided sub-types.
- [ ] Changes to grandchild embedded document updates.
- [ ] Changes to unlinked token and `ActorDelta` behaviour.
- [ ] New descendant methods and deprecation of old methods.
- [ ] New `CONFIG.Actor.trackableAttributes` and `TokenDocument.getTrackedAttributes` behaviour.

**Comment by tposney** [comment]
Yes please - these are big issues for my modules and any guidance would be very greatefully received.
Other candidates for migration guides:
changes to status effects to have a set of statuses rather than a statusId - impacts several modules.
impact of an activeEffect description field which collides with various modules that already have such.
impact of non legacy transfer effect application (and confirmation that it will respect suppressed/disabled from item status in dnd5e).
confirmation of intended behaviour of non-transfer effects, do they affect the item on which they exist or are they intended for other purposes (i.e. transfer to target on item use).

**Comment by Fyorl** [comment]
>changes to status effects to have a set of statuses rather than a statusId - impacts several modules

This seems like a good candidate, I've added it.

>impact of an activeEffect description field which collides with various modules that already have such

I'm not sure I understand this one. Are you saying there are existing modules that add a `description` field to the `ActiveEffect` Document? I wouldn't have thought that was possible. The `DataModel` should throw away any fields that are not in the schema.

>impact of non legacy transfer effect application (and confirmation that it will respect suppressed/disabled from item status in dnd5e)

I've added `legacyTransferral` to the list of topics, though any documentation or guide will not go into specifics on the dnd5e system. I can answer your question here though that the plan is for the initial v11-ready release of dnd5e to ship with `legacyTransferral` left as the default (i.e. `true`).

>confirmation of intended behaviour of non-transfer effects, do they affect the item on which they exist or are they intended for other purposes (i.e. transfer to target on item use).

This can be discussed in the guide but, for now, the behaviour of `transfer: false` effects is unchanged from v10, i.e. they have no special behaviour and are simply stored on the Item.

**Comment by LebombJames** [comment]
Could the changes to MeasuredTemplates be added? Starfinder's template overrides silently fail on V11.

**Comment by Fyorl** [comment]
> Could the changes to MeasuredTemplates be added? Starfinder's template overrides silently fail on V11, and I'm not sure where to start in updating them.

I'm not familiar with the MeasuredTemplate changes and whether they might warrant a migration guide or not. It's worth reaching out to @Feu-Secret or @aaclayton though as we are open to amending the core implementation in certain circumstances in order to avoid adversely impacting systems with the v11 changes.

**Comment by LebombJames** [comment]
I don't think reverting core changes will be necessary; our overrides are quite hacky and monkeypatch core, so they could do with a refactor. I'm just looking for some guidance as to best practices on how to do that now. Will reach out on discord, thanks

**Comment by anthonyronda** [comment]
We adopted V10 System Models, and I would like to see migration guidance (maybe a one-liner?) on the following deprecation warnings

```js
Error: You are accessing CONFIG.Item.systemDataModels which is deprecated. Please use CONFIG.Item.dataModels instead.
Deprecated since Version 11
Backwards-compatible support will be removed in Version 13
```

```js
Error: You are accessing CONFIG.Actor.systemDataModels which is deprecated. Please use CONFIG.Actor.dataModels instead.
Deprecated since Version 11
Backwards-compatible support will be removed in Version 13
```

**Comment by aaclayton** [comment]
> We adopted V10 System Models, and I would like to see migration guidance (maybe a one-liner?) on the following deprecation warnings

Sure thing @anthonyronda we can add this to the list, but is the warning message not self-explanatory in this case? Could the message be worded more clearly? You simply have to switch from `CONFIG.Item.systemDataModels` to `CONFIG.Item.dataModels`. All other aspects of usage remain the same. What would make this more clear?

**Comment by anthonyronda** [comment]
> What would make this more clear?

It is indeed self-explanatory in this case, but I suppose I have some fear of the possibility of more hidden deprecations and breaking changes, and by providing this example of something that I haven't seen addressed, I could one way or another reveal anything else in the System data models category. I provided the warning I get here which triggers on init, but I haven't found other examples such as when I use one of a document's getters.

A comprehensive migration guide provides peace of mind, and the thought that perhaps my perception that it might get skipped in the migration guide provides space for doubting thoughts to creep in.

**Comment by aaclayton** [comment]
My view is that a change that has (1) a multi-generation backwards compatible deprecation window and (2) a clear console warning that explains exactly what has changed is not a "hidden deprecation" nor is it an *immediately* breaking change. 

There are probably around 25 such cases in V11. We can provide a bullet point list of them in our migration article, but I don't think they need a "guide" per-se since the change is self-evident.

**Comment by NekroDarkmoon** [comment]
There's also a migration from `ActiveEfffect.label` to `ActiveEffect.name`. Any modules or systems that had `name` as a getter on their ActiveEffect class end up with an error instead of a deprecation warning so it may be useful to add that to the migration guide. 

> I'm not sure I understand this one. Are you saying there are existing modules that add a description field to the ActiveEffect Document? I wouldn't have thought that was possible. The DataModel should throw away any fields that are not in the schema.

This would be the same case where a getter for a description was defined to get easy access to a description field from flags.
