### ISSUE TITLE
Develop generalized "Scene Regions" as an embedded Document and Placeable Object type within a Scene allowing users to define geometric regions with sub-types which determine their behavior.

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/foundryvtt#9772]
Technical foundation which affects or encompasses some of the following:
- Event Triggers (uses both data structures and UX)
- Terrain Areas (both data structures and UX)
- Environmental Special Effects (both data structure and UX)
- Simple Fog Management (potentially uses data structure, definitely uses UX)
- Custom Ambient Sound Shapes (UX only)
- Custom Light Source Shapes (UX only)
- Improved Drawing Tools (UX only)
- Improved Measured Templates (UX only)

## Region Behaviors
- #10388 
- #10389 
- #10390
- Triggered script behavior
- Triggered macro behavior
- Combat encounter behavior
- Game pause behavior

## Requirements
The Scene Regions feature must support the following requirements. This issue needs to be split up with each of the below bullet points linking out to an individual issue for prioritization and work.

### Data Model
- A data model and processing framework for defining areas of a scene using geometric shapes.
- Support complex polygons which include holes.
- Support shape unions or intersections where a region is defined as the composite of multiple shapes.

### UI/UX
- A UX layer and set of canvas interaction tools which standardize the way that users define regions.
- A UI configuration sheet for viewing and modifying the properties of a region.

### API
- Provide a robust set of API methods for interacting with Scene Regions.
- Allow each region to specify its own interactivity conditions.
- Expose events (hooks?) which trigger when regions become active or inactive.

## Ongoing To-Do List
- [ ] Decide on what the snapping behavior of Scene Regions should be (if any)
- [ ] Decide whether we want to prevent Scene Regions (or any Placeable type in general) from being copy+pasteable
- [ ] Decide how to optimally compute bounds for the region
- [ ] Replace code for drawing regions once we have combined shapes

**Comment by rapus95** [comment]
It would be nice if that also allows arbitrary tagging of regions. And then allow spacial sorting and filtering the list of regions for having a certain tag. 

Like if you set up your map with lighting areas (some with ambient light and some without), those regions could be tagged with "lighting" and then you can select to only show areas which have that tag. Otherwise, this will become very cumbersome to work with. Both visually as well as performancewise. And if these tags can be arbitrary, modules can jump in and use that for their own purposes. Is that, what you meant with "sub-types which determine their behavior"?

Having arbitrary geometric shapes, paired with being taggable, is basically enough for a damn powerful framework, I guess that's why it's an EPIC. Everything from configuration, rendering, interaction and so on, including all features you named in the issue, could then be implemented as ordinary modules. (In particular, if #10203 will also find its way into core).
Eveything's a module sounds like it was too good to be true. But I'll hope :D

Given this will be used a lot, the most effort should go into the data structure that holds the regions, so that it allows for efficient filtering and spacial sorting.

**Comment by aaclayton** [comment]
Moving issued to P2 for continued work!
